.TH "deepin-scanner" "1" "2021-1-28" "Deepin"
.SH NAME
deepin-scanner
.SH DESCRIPTION
a tool for reading document files,supporting PDF, DJVU, DOCX etc
.SH SYNOPSIS
deepin-scanner [FILE(s)...] [OPTIONS...]
.SH OPTIONS
.PP
-thumbnail    tell deepin-scanner to generate thumbnail of PDF file
.PP
-f -filePath    thumbnail source file,this option needs to be set after -thumbnail
.PP
-t -thumbnailPath    thumbnail generation path,this option needs to be set after -thumbnail
.SH SEE ALSO
https://github.com/linuxdeepin/deepin-scanner
.SH AUTHOR
.PP
.B deepin-scanner
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT yangwu@\:uniontech.com
re2zero
.ME
for the Debian Project (but may be used by others)
