.TH "deepin-scanner" "1" "2025-4-28" "Deepin"
.SH NAME
deepin-scanner
.SH DESCRIPTION
a tool for scan document,supports a variety of scanning devices.
.SH SYNOPSIS
deepin-scanner [FILE(s)...] [OPTIONS...]
.SH OPTIONS
.PP
.SH SEE ALSO
https://github.com/linuxdeepin/deepin-scanner
.SH AUTHOR
.PP
.B deepin-scanner
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT yangwu@\:uniontech.com
re2zero
.ME
for the Debian Project (but may be used by others)
